### ISSUE TITLE
fails to send email when to or from contains display name

### ISSUE THREAD

**Issue by hwmrocker** [hwmrocker/smtplibaio#10]
When the TO: or FROM: email contains a display name like `"display name" <email@addr.com>`
the original smtplib can handle this format.

I have a local fix and push it tomorrow.

**Comment by Frzk** [comment]
I wittingly removed this feature when working on the 2.0 branch. The RFC is not really clear about this, but all examples given in it only specify an e-mail address (i.e. `<bob@example.org>`).
My goal was to stick as close as possible with the RFC. But that's arguable :)

Anyway, it also led me to notice our second example is kinda wrong : we should pass the `addr_spec` attribute of the `email.headerregistry.Address` objects rather than their string representations.

A PR for this is ready (#11)
